### ISSUE TITLE
Add pings/statues back from comradio2 to comradio3

### ISSUE THREAD

**Issue by techs-sus** [fofl12/scriptsoup#2]
### comradio3 is a great protocol, but it's simply not as _featureful_ as comradio2

I **love** comradio3 but cannot get enough of pings/statues or even the old diffieHellmanExchange type that comradio2 had.
Also from a feature perspective, it makes more sense to add on to comradio2 because it will be easier to transition from the old protocol to the new one.

**Comment by fofl12** [comment]
Hi Tech, I didn't add as many features to comradio3 as comradio2, because I think that most of them don't make any sense and don't fit very well in the environment that comradio was made for.

Examples: pings *might* make sense in services like Discord where the central server can notify the clients, but not in comradio because none of the clients connected might always be online and making a central service would just remove the point of MessagingService.
Statuses were useless, since you can just use the default "text" type instead. If you used them to notify others when your client did something, you can use the "action" type which covers a broader spectrum of use cases.

However, if you are interested in the old diffieHellmanExchange type, please do suggest how it could be implemented! I really don't like the way that it was implemented in comradio2.

**Comment by techs-sus** [comment]
I see! Thanks!
